name: Docker CI

on:
  push:
    branches:
      - 'develop'
    tags:
      - 'releases/*'

jobs:
  build_push:
    name: Build image and push to dockerhub
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Docker Metadata action
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: grmontesino/transmission
          tags: |
            type=edge,branch=develop
            type=match,pattern=releases-(.*),group=1

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: ./docker
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
